trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  FLUTTER_VERSION: 'stable'  # You can change this to any specific version if needed

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa

    # Install Flutter
    git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION --depth 1
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter doctor

    # Pre-cache Flutter packages
    flutter precache

    # Install dependencies
    flutter pub get
  displayName: 'Install Dependencies and Flutter SDK'

- script: |
    # Run Flutter tests
    flutter test
  displayName: 'Run Flutter Tests'

- script: |
    # Analyze the project
    flutter analyze > analysis_result.log
  displayName: 'Run Flutter Analyze'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloudcon1'  
    organization: 'backbenchers326'  
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(Build.Repository.Name)'  
    cliSources: '.'
    extraProperties: |
      sonar.host.url=https://sonarcloud.io
      sonar.exclusions=**/*.g.dart,**/*.freezed.dart
      sonar.tests=test
      sonar.test.inclusions=**/*_test.dart
      sonar.branch.name=$(Build.SourceBranchName)
      sonar.dart.sdk=E:/Flutter Dev/flutter/bin/cache/dart-sdk  # Replace with your Dart SDK path

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
