trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  FLUTTER_VERSION: 'stable'  # You can change this to any specific version if needed

steps:
- script: |
    curl -s https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_2.10.3-stable.zip -o flutter.zip
    tar xf flutter.zip
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter --version
  displayName: 'Install Flutter'

- script: flutter precache
  displayName: 'Pre-cache Flutter Packages'

- script: flutter pub get
  displayName: 'Install Flutter Dependencies'

- script: flutter test
  displayName: 'Run Flutter Tests'

- script: flutter analyze > analysis_result.log
  displayName: 'Run Flutter Analyze'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloudcon1'  
    organization: 'backbenchers326'  
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(Build.Repository.Name)'  
    cliSources: '.'
    extraProperties: |
      sonar.host.url=https://sonarcloud.io
      sonar.exclusions=**/*.g.dart,**/*.freezed.dart
      sonar.tests=test
      sonar.test.inclusions=**/*_test.dart
      sonar.branch.name=$(Build.SourceBranchName)
      sonar.dart.sdk=E:/Flutter Dev/flutter/bin/cache/dart-sdk  # Replace with your Dart SDK path

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

