trigger:
  batch: true

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseFlutter@1
    inputs:
      version: 'latest'

  - script: |
      flutter pub get
      flutter build apk
    displayName: 'Install dependencies and build Flutter app'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'default-organization'
      scannerMode: 'CLI'
      projectKey: 'my-flutter-app'
      projectName: 'My Flutter App'
      extraProperties: |
        sonar.sources=lib
        sonar.exclusions=**/**/test/**

  - script: |
      sonar-scanner
    displayName: 'Run SonarCloud analysis'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'