trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool:
  vmImage: 'windows-latest'

steps:
- task: UseFlutter@1
  inputs:
    version: 'latest'

- script: |
    flutter pub get
    flutter analyze
  displayName: 'Install dependencies and run Flutter analyze'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'MySonarCloudServiceConnection'
    organization: 'myorganization'
    scannerMode: 'CLI'
    projectKey: 'myprojectkey'
    projectName: 'MyProjectName'
    extraProperties: |
      sonar.sources=lib
      sonar.exclusions=**/test/**

- script: |
    sonar-scanner
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
